% Here I initialize all those variables that must not change neither during
% montecarlo nor during time simulation.
% In particular the requirement for P.nodes is also to preallocate before
% calling multilayer_checkpars.m in which P.nodes information must be used!

%% proj

% proj    = struct(   'description',  {},     ...
%                     'ipath',        {},     ...
%                     'opath',        {}      ...
%                 );
%% B
% B       = struct(   'top',      {},     ...
%                     'bot',      {},     ...
%                     'Ctop',     {}      ...
%                 );
%% M
% M       = struct(   '',{},      ...
%                     '',{}       ...
%                 );
% %% O
% O       = struct(   'files',{}, ...
%                     '',{}       ...
%                 );
% %% P
% P       = struct(   '',{},      ...
%                     '',{}       ...
%                 );
% %% S
% S       = struct(   '',{},      ...
%                     '',{}       ...
%                 );
% %% V
% V       = struct(   '',{},      ...
%                     '',{}       ...
%                 );
% %% W
% W       = struct(   '',{},      ...
%                     '',{}       ...
%                 );

%% SOIL GRID GEOMETRY
% --nodes
% P.nodes.num                     = NaN( W.nlay+0,    1 );
% P.nodes.thickness               = NaN( W.nlay+0,    1 );
% P.nodes.cumsum                  = NaN( W.nlay+1,    1 );
% P.nodes.soillayer               = NaN( P.nz+1,      1 );
% P.nodes.z                       = NaN( P.nz+1,      1 );
% P.nodes.dz                      = NaN( P.nz+1,      1 );
%% end